version: '3.7'

services:
  app:
    image: nginx:1.16.1
    container_name: app
    environment:
      NODE_ENV: production
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/var/www/ssl
      - ./dist/VNSOS/:/var/www/html/
    depends_on:
      - node
    ports:
      - "80:80"
      - "443:443"
  node:
    image: node:14-alpine
    container_name: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - ~/.yarn:/home/node/.yarn
      - /home/node/app/node_modules
    command:  >
      sh -c "yarn &&
            yarn build"